#main
log_file_path: './scoring_api.log'
salt: 'charon'
admin_login: 'ferryman'
admin_salt: 42

#redis
redis_host: '127.0.0.1'
redis_port: 6379
redis_db: 0
redis_reconnect_try: True
redis_reconnect_attempt: 5
redis_reconnect_timeout: 1
redis_reconnect_smart_delay: True

#http:
HTTP_200_OK: 200
HTTP_400_BAD_REQUEST: 400
HTTP_403_FORBIDDEN: 403
HTTP_404_NOT_FOUND: 404
HTTP_422_UNPROCESSABLE_ENTITY: 422
HTTP_500_INT_SERV_ERROR: 500
